import { User } from 'src/auth/user.entity';
import { BaseEntity, Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { TaskStatus } from './task-status.enum';


@Entity()
export class Task extends BaseEntity {
    @PrimaryGeneratedColumn() //primary key, should be auto generated and incremented by postgres
    id: number;

    @Column()
    title: string;

    @Column()
    description: string;
    
    @Column()
    status: TaskStatus;

    //define the relationship, not a column  
    @ManyToOne(type => User, user => user.tasks, {eager: false})
    user: User;

    @Column()
    userId: number; //this is auto generated by the db, but we have to define the column ourselves...
}